### ISSUE TITLE
[Backend Developer] - Version Control

### ISSUE THREAD

**Issue by margach** [kamranahmedse/roadmap.sh#57] opened 2019-12-06 12:02 UTC
Before you write a line of code, learn what version control is and related tools to use it like Git.

**Comment by puthuppu** [comment] 2019-12-18 15:56
Honestly this applies to more than just backend.  It seems like it should be a per-requisite to Frontend, Backend, DevOps, etc.

**Comment by margach** [comment] 2019-12-18 16:29
I agree, but should be added as part of the learning journey since it has a steep learning curve, starting early is best.

**Comment by puthuppu** [comment] 2019-12-18 18:03
Agreed, my point was it should probably be part of more than just the Backend Developer road map.  It should either be before the language component or a flyout of the language component.

**Comment by Lennert-Onyx** [comment] 2019-12-20 12:02
Duplicate of #39?

Git is first item in [the common section](https://github.com/kamranahmedse/developer-roadmap#introduction).

**Closed** 2019-12-20 14:43 UTC
